export const siteData = {
  siteName: "LocalLegalGuides",
  siteTagline: "Local legal guides by city",
  siteDescription:
    "Local legal guides for DUI, DWI, personal injury, city courts, agencies, deadlines, and official local resources.",
  domain: "locallegalguides.com",
  legalEmail: "legal@locallegalguides.com",
  privacyEmail: "privacy@locallegalguides.com",
  sponsorsEmail: "sponsors@locallegalguides.com",
  lastVerified: "2026-05-07",
  year: 2026,
  sponsorPackages: {
    "madison-county-il": {
      status: "available",
      annualPriceUsd: 1000,
      termLabel: "12-month exclusive package",
      coverageLabel: "5 Illinois cities across DUI and personal injury pages",
      sponsor: {
        firmName: "",
        attorneyName: "",
        phone: "",
        ctaUrl: "",
        officeAddress: "",
        serviceArea: "",
        shortBio: "",
        photoUrl: "",
        disclaimer: "Attorney Advertising. Sponsorship does not imply endorsement.",
      },
    },
    "st-charles-county-mo": {
      status: "preview",
      annualPriceUsd: 1000,
      termLabel: "12-month exclusive package",
      coverageLabel: "5 Missouri cities across DWI and personal injury pages",
      sponsor: {
        firmName: "Your Firm Here",
        attorneyName: "Sponsor Preview",
        phone: "(555) 010-2000",
        ctaUrl: "/contact/",
        officeAddress: "Demo placement shown for St. Charles County package previews.",
        serviceArea: "St. Charles County sponsor package preview",
        shortBio:
          "This is a sample sponsor profile to show attorneys exactly how a sold regional package would appear on the cluster page and the related city guides.",
        photoUrl: "",
        disclaimer: "Preview sponsor card for sales demos only. Replace with real sponsor details before launch.",
      },
    },
    "west-st-louis-county-mo": {
      status: "available",
      annualPriceUsd: 1000,
      termLabel: "12-month exclusive package",
      coverageLabel: "5 Missouri cities across DWI and personal injury pages",
      sponsor: {
        firmName: "",
        attorneyName: "",
        phone: "",
        ctaUrl: "",
        officeAddress: "",
        serviceArea: "",
        shortBio: "",
        photoUrl: "",
        disclaimer: "Attorney Advertising. Sponsorship does not imply endorsement.",
      },
    },
    "charlotte-south-nc": {
      status: "available",
      annualPriceUsd: 1000,
      termLabel: "12-month exclusive package",
      coverageLabel: "4 North Carolina cities across DWI and personal injury pages",
      sponsor: {
        firmName: "",
        attorneyName: "",
        phone: "",
        ctaUrl: "",
        officeAddress: "",
        serviceArea: "",
        shortBio: "",
        photoUrl: "",
        disclaimer: "Attorney Advertising. Sponsorship does not imply endorsement.",
      },
    },
    "raleigh-north-nc": {
      status: "available",
      annualPriceUsd: 1000,
      termLabel: "12-month exclusive package",
      coverageLabel: "4 North Carolina cities across DWI and personal injury pages",
      sponsor: {
        firmName: "",
        attorneyName: "",
        phone: "",
        ctaUrl: "",
        officeAddress: "",
        serviceArea: "",
        shortBio: "",
        photoUrl: "",
        disclaimer: "Attorney Advertising. Sponsorship does not imply endorsement.",
      },
    },
    "wake-southwest-nc": {
      status: "available",
      annualPriceUsd: 1000,
      termLabel: "12-month exclusive package",
      coverageLabel: "4 North Carolina cities across DWI and personal injury pages",
      sponsor: {
        firmName: "",
        attorneyName: "",
        phone: "",
        ctaUrl: "",
        officeAddress: "",
        serviceArea: "",
        shortBio: "",
        photoUrl: "",
        disclaimer: "Attorney Advertising. Sponsorship does not imply endorsement.",
      },
    },
  },
  legalBasics: {
    IL: {
      duiName: "DUI",
      duiThreshold: "0.08% BAC",
      duiCharge: "A first DUI is generally a Class A misdemeanor unless aggravating facts apply.",
      duiLicense:
        "A statutory summary suspension is separate from the criminal case and can begin 46 days after notice.",
      personalInjuryDeadline:
        "Illinois generally gives two years to file personal injury claims, though claims involving government defendants can have shorter notice rules.",
      injuryVenue:
        "Injury lawsuits are usually filed in the county where the crash or injury happened, or where a defendant can be sued.",
      sources: [
        {
          label: "Illinois DUI statute",
          href: "https://www.ilga.gov/documents/legislation/ilcs/documents/062500050K11-501.htm",
        },
        {
          label: "Illinois Secretary of State DUI information",
          href: "https://www.ilsos.gov/departments/drivers/traffic-safety/dui.html",
        },
        {
          label: "Illinois license reinstatement guidance",
          href: "https://www.ilsos.gov/departments/baiid/reinstate.html",
        },
        {
          label: "Illinois personal injury limitations period",
          href: "https://www.ilga.gov/legislation/ilcs/fulltext.asp?DocName=073500050K13-202",
        },
      ],
    },
    MO: {
      duiName: "DWI",
      duiThreshold: "0.08% BAC",
      duiCharge: "Missouri treats driving while intoxicated as a criminal case, with penalties increasing for prior offenses and aggravating facts.",
      duiLicense:
        "A DWI arrest can create a separate administrative license case through the Missouri Department of Revenue.",
      personalInjuryDeadline:
        "Missouri generally uses a five-year limitations period for personal injury claims.",
      injuryVenue:
        "Civil injury lawsuits are usually filed in the circuit court connected to the county where venue is proper.",
      sources: [
        {
          label: "Missouri DWI statute",
          href: "https://revisor.mo.gov/main/OneSection.aspx?section=577.010",
        },
        {
          label: "Missouri administrative alcohol law",
          href: "https://dor.mo.gov/driver-license/revocation-suspension/intoxication.html",
        },
        {
          label: "Missouri personal injury limitations period",
          href: "https://revisor.mo.gov/main/OneSection.aspx?section=516.120",
        },
      ],
    },
    NC: {
      duiName: "DWI",
      duiThreshold: "0.08% alcohol concentration",
      duiCharge: "North Carolina prosecutes impaired driving under G.S. 20-138.1, with sentencing levels based on aggravating and mitigating factors.",
      duiLicense:
        "A DWI arrest can create immediate license consequences, including a civil revocation in qualifying cases.",
      personalInjuryDeadline:
        "North Carolina generally gives three years for personal injury claims.",
      injuryVenue:
        "Civil injury lawsuits are filed through the county court system when venue is proper there.",
      sources: [
        {
          label: "North Carolina impaired driving statute",
          href: "https://www.ncleg.gov/EnactedLegislation/Statutes/HTML/BySection/Chapter_20/GS_20-138.1.html",
        },
        {
          label: "North Carolina DWI sentencing statute",
          href: "https://www.ncleg.gov/EnactedLegislation/Statutes/HTML/BySection/Chapter_20/GS_20-179.html",
        },
        {
          label: "North Carolina personal injury limitations period",
          href: "https://www.ncleg.gov/EnactedLegislation/Statutes/HTML/BySection/Chapter_1/GS_1-52.html",
        },
      ],
    },
  },
  practiceAreas: [
    {
      slug: "dui",
      label: "DUI",
      title: "DUI Legal Guide",
      summary:
        "Driving under the influence, license suspension, court process, and local agencies.",
    },
    {
      slug: "personal-injury",
      label: "Personal Injury",
      title: "Personal Injury Legal Guide",
      summary:
        "Car crashes, slip-and-fall claims, and the local court and filing process.",
    },
  ],
  regions: [
    {
      slug: "madison-county-il",
      name: "Madison County Metro East",
      state: "Illinois",
      stateCode: "IL",
      teaser: "Metro East guides centered on Edwardsville and surrounding Madison County cities.",
      urgentDeadline: {
        headline: "Illinois DUI timing can move before the first full court strategy is in place.",
        body: "Madison County drivers often need to track the criminal case, police records, and Illinois Secretary of State license consequences at the same time.",
      },
      regionHighlights: [
        {
          title: "Interstate-heavy enforcement pattern",
          body: "This Metro East cluster sits along I-55, I-70, I-255, and Route 159 corridors, so stops can involve city police, the sheriff, or Illinois State Police depending on where the contact started.",
        },
        {
          title: "Edwardsville is the county anchor",
          body: "Even when the stop or crash happened in Collinsville, Glen Carbon, Maryville, or Troy, readers usually end up orienting around the Edwardsville courthouse and related county offices.",
        },
        {
          title: "Criminal and records paths can split",
          body: "Madison County has separate court, clerk, and criminal justice touchpoints, which is why this region page helps before someone chases the wrong building or office window.",
        },
        {
          title: "State police overlap matters here",
          body: "Because the cluster includes major highway traffic near the St. Louis edge, state-patrol involvement is more common than in a purely residential suburb cluster.",
        },
      ],
      processNotes: [
        {
          label: "Highway stops",
          title: "Figure out whether the stop was municipal, county, or state",
          body: "That first question can change where police records come from and which enforcement office a reader needs to contact before a court date.",
        },
        {
          label: "Court buildings",
          title: "Madison County uses more than one criminal-justice touchpoint",
          body: "Readers should confirm whether they need the main courthouse, the circuit clerk, or a criminal-justice building before showing up in Edwardsville.",
        },
        {
          label: "Driver services",
          title: "License questions usually point back to the Edwardsville driver-services office",
          body: "That makes the region page useful for sorting out state-level license issues before drilling down into one city guide.",
        },
      ],
      court: {
        name: "Madison County Courthouse",
        address: "155 N. Main Street, Edwardsville, IL 62025",
        phone: "(618) 296-4470",
        hours: "Monday-Friday, 8:30 am-4:30 pm",
        courtSystem: "Third Judicial Circuit",
        href: "https://www.illinoiscourts.gov/courts-directory/100/Madison-County-Courthouse/court/",
      },
      courtOffices: [
        {
          name: "Madison County Courthouse",
          type: "Circuit Court",
          address: "155 N. Main Street, Edwardsville, IL 62025",
          phone: "(618) 296-4470",
          hours: "Monday-Friday, 8:30 am-4:30 pm",
          href: "https://www.illinoiscourts.gov/courts-directory/100/Madison-County-Courthouse/court/",
          note: "Primary courthouse for Madison County Circuit Court matters.",
        },
        {
          name: "Madison County Circuit Clerk",
          type: "Court records and filings",
          address: "155 N. Main Street, Edwardsville, IL 62025",
          phone: "(618) 692-6240",
          hours: "Call to confirm counter hours before visiting.",
          href: "https://www.madisoncountyil.gov/departments/circuit_clerk/index.php",
          note: "Use for case records, fines, court dates, and filing questions.",
        },
        {
          name: "Madison County Criminal Justice Center",
          type: "Criminal court location",
          address: "509 Ramey Street, Edwardsville, IL 62025",
          phone: "(618) 692-8932",
          hours: "Call to confirm the correct courtroom before appearing.",
          href: "https://www.madcosao.gov/faq",
          note: "The Madison County State's Attorney FAQ lists this as a court location for some criminal appearances.",
        },
      ],
      sharedEnforcement: [
        {
          name: "Madison County Sheriff's Office",
          type: "County Sheriff",
          address: "405 Randle Street, Edwardsville, IL 62025",
          phone: "(618) 692-4433",
          href: "https://www.madisoncountyil.gov/departments/sheriff/index.php",
          note: "County agency that may be involved outside municipal limits or on county matters.",
        },
        {
          name: "Illinois State Police - District 11",
          type: "State Police",
          address: "1100 Eastport Plaza Drive, Collinsville, IL 62234",
          phone: "(618) 346-3990",
          href: "https://isp.illinois.gov/",
          note: "State patrol agency for highways and state-level traffic enforcement.",
        },
      ],
      licenseOffice: {
        name: "Illinois Secretary of State Driver Services Facility - Edwardsville",
        type: "Driver Services",
        address: "1502A Troy Road, Edwardsville, IL 62025",
        phone: "(618) 656-8956",
        hours: "Hours change periodically; confirm with the Secretary of State before visiting.",
        href: "https://www.ilsos.gov/",
        note: "Nearest full driver services reference for licenses, IDs, written testing, road testing, CDL written testing, registration, titles, and plates.",
      },
      cities: [
        {
          slug: "collinsville-il",
          name: "Collinsville",
          agency: "Collinsville Police Department",
          police: {
            name: "Collinsville Police Department",
            type: "Municipal Police",
            address: "200 W. Clay Street, Collinsville, IL 62234",
            phone: "(618) 344-2131",
            hours: "Front desk and records hours vary; call before visiting.",
            href: "https://www.collinsvilleil.org/departments/police-department/",
            note: "For city police records, local crash reports, and municipal law-enforcement questions.",
          },
        },
        {
          slug: "edwardsville-il",
          name: "Edwardsville",
          agency: "Edwardsville Police Department",
          police: {
            name: "Edwardsville Police Department",
            type: "Municipal Police",
            address: "333 S. Main Street, Edwardsville, IL 62025",
            phone: "(618) 656-2131",
            href: "https://www.cityofedwardsville.com/police",
            note: "For city police records, local crash reports, and municipal law-enforcement questions.",
          },
        },
        {
          slug: "glen-carbon-il",
          name: "Glen Carbon",
          agency: "Glen Carbon Police Department",
          police: {
            name: "Glen Carbon Police Department",
            type: "Municipal Police",
            address: "149 N. Main Street, Glen Carbon, IL 62034",
            phone: "(618) 288-7226",
            href: "https://www.glencarbonil.gov/187/Police-Department",
            note: "For village police records, local crash reports, and municipal law-enforcement questions.",
          },
        },
        {
          slug: "maryville-il",
          name: "Maryville",
          agency: "Maryville Police Department",
          police: {
            name: "Maryville Police Department",
            type: "Municipal Police",
            address: "2500 N. Center Street, Maryville, IL 62062",
            phone: "(618) 344-8899",
            hours: "Lobby open 24 hours; business office generally Monday-Friday, 8:00 am-4:30 pm.",
            href: "https://www.vil.maryville.il.us/99/Police",
            note: "For village police records, local crash reports, and municipal law-enforcement questions.",
          },
        },
        {
          slug: "troy-il",
          name: "Troy",
          agency: "Troy Police Department",
          police: {
            name: "Troy Police Department",
            type: "Municipal Police",
            address: "116 E. Market Street, Troy, IL 62294",
            phone: "(618) 667-6731",
            href: "https://www.troyil.us/238/Police-Department",
            note: "For city police records, local crash reports, and municipal law-enforcement questions.",
          },
        },
      ],
    },
    {
      slug: "st-charles-county-mo",
      name: "St. Charles County",
      state: "Missouri",
      stateCode: "MO",
      teaser: "West of St. Louis, with five city hubs and two practice areas.",
      urgentDeadline: {
        headline: "Missouri DWI cases can trigger a separate driver-license track quickly.",
        body: "In St. Charles County, drivers often need to think about the circuit court case and Missouri Department of Revenue consequences on parallel timelines.",
      },
      regionHighlights: [
        {
          title: "One county, several growth corridors",
          body: "This cluster covers fast-growing communities tied together by I-70, Highway K, and the western St. Charles County development corridor, which means traffic enforcement patterns can differ sharply by city.",
        },
        {
          title: "The county seat still drives the court path",
          body: "Even for O'Fallon, Wentzville, and Lake Saint Louis readers, the county court anchor stays in St. Charles, so the regional page helps explain the shared court system.",
        },
        {
          title: "License logistics are spread out",
          body: "Some drivers are closer to O'Fallon or Wentzville license offices while others are closer to St. Charles, which makes a county-level orientation page more useful than a single-city view.",
        },
        {
          title: "Municipal police are not interchangeable",
          body: "The cluster uses separate city departments, so report retrieval and local records questions can change even when the court system is shared.",
        },
      ],
      processNotes: [
        {
          label: "Court anchor",
          title: "The criminal court path still funnels back to St. Charles",
          body: "Readers can use the region page to connect western and central county cities to the same circuit-court structure before relying on city-level details.",
        },
        {
          label: "High-growth suburbs",
          title: "Traffic corridors can change which police agency starts the case",
          body: "Stops near I-70 or major connector roads can feel more regional than purely neighborhood-based, which is why the cluster page carries extra value.",
        },
        {
          label: "License offices",
          title: "Western county drivers may use different DOR touchpoints",
          body: "O'Fallon and Wentzville readers often care less about the county seat than about the closest workable license-office counter, so this page keeps both layers visible.",
        },
      ],
      court: {
        name: "St. Charles County Circuit Court",
        address: "300 N. Second Street, St. Charles, MO 63301",
        phone: "(636) 949-3080",
        hours: "Monday-Friday, 8:00 am-5:00 pm",
        courtSystem: "11th Judicial Circuit",
        href: "https://www.courts.mo.gov/page.jsp?id=321",
      },
      licenseOffice: {
        name: "St. Charles License Office",
        type: "Missouri License Office",
        address: "2499 Raymond Drive, St. Charles, MO 63301",
        phone: "(636) 946-4456",
        hours: "Confirm current hours with the Missouri Department of Revenue office locator.",
        href: "https://dor.mo.gov/license-office-locator/",
        note: "Missouri DOR offices handle driver-license transactions and can confirm the correct location before a visit.",
      },
      cities: [
        {
          slug: "lake-saint-louis-mo",
          name: "Lake Saint Louis",
          agency: "Lake Saint Louis Police Department",
          police: {
            name: "Lake Saint Louis Police Department",
            type: "Municipal Police",
            address: "200 Civic Center Drive, Lake Saint Louis, MO 63367",
            phone: "(636) 625-8018",
            href: "https://www.lakesaintlouis.com/154/Police",
            note: "For city police records, crash reports, and law-enforcement questions inside Lake Saint Louis.",
          },
          licenseOfficeOverride: {
            name: "Wentzville License Office",
            type: "Missouri License Office",
            address: "807-B E. Pearce Boulevard, Wentzville, MO 63385",
            phone: "(636) 445-5053",
            hours: "Confirm current hours with the Missouri Department of Revenue office locator.",
            href: "https://dor.mo.gov/license-office-locator/",
            note: "Nearest listed Missouri DOR license-office option for many western St. Charles County drivers.",
          },
        },
        {
          slug: "ofallon-mo",
          name: "O'Fallon",
          agency: "O'Fallon Police Department",
          police: {
            name: "O'Fallon Police Department",
            type: "Municipal Police",
            address: "1019 Bryan Road, O'Fallon, MO 63366",
            phone: "(636) 240-3200",
            href: "https://www.ofallon.mo.us/police",
            note: "For city police reports, local crash records, and O'Fallon law-enforcement questions.",
          },
          licenseOfficeOverride: {
            name: "O'Fallon License Office",
            type: "Missouri License Office",
            address: "2421 Highway K, O'Fallon, MO 63368",
            phone: "(636) 394-5829",
            hours: "Confirm current hours with the Missouri Department of Revenue office locator.",
            href: "https://dor.mo.gov/license-office-locator/",
            note: "Missouri DOR license office serving O'Fallon-area driver-license and motor-vehicle transactions.",
          },
        },
        {
          slug: "st-charles-mo",
          name: "St. Charles",
          agency: "St. Charles Police Department",
          police: {
            name: "St. Charles Police Department",
            type: "Municipal Police",
            address: "1781 Zumbehl Road, St. Charles, MO 63303",
            phone: "(636) 949-3300",
            href: "https://www.stcharlescitymo.gov/166/Police",
            note: "For city police records, traffic crash reports, and local law-enforcement questions.",
          },
        },
        {
          slug: "st-peters-mo",
          name: "St. Peters",
          agency: "St. Peters Police Department",
          police: {
            name: "St. Peters Police Department",
            type: "Municipal Police",
            address: "1020 Grand Teton Drive, St. Peters, MO 63376",
            phone: "(636) 278-2222",
            href: "https://www.stpetersmo.net/254/Police-Department",
            note: "For St. Peters police reports, local crash records, and municipal enforcement questions.",
          },
        },
        {
          slug: "wentzville-mo",
          name: "Wentzville",
          agency: "Wentzville Police Department",
          police: {
            name: "Wentzville Police Department",
            type: "Municipal Police",
            address: "1019 Schroeder Creek Boulevard, Wentzville, MO 63385",
            phone: "(636) 327-5105",
            href: "https://www.wentzvillemo.gov/police/",
            note: "For Wentzville police records, local crash reports, and city enforcement questions.",
          },
          licenseOfficeOverride: {
            name: "Wentzville License Office",
            type: "Missouri License Office",
            address: "807-B E. Pearce Boulevard, Wentzville, MO 63385",
            phone: "(636) 445-5053",
            hours: "Confirm current hours with the Missouri Department of Revenue office locator.",
            href: "https://dor.mo.gov/license-office-locator/",
            note: "Missouri DOR license office serving Wentzville-area driver-license and motor-vehicle transactions.",
          },
        },
      ],
    },
    {
      slug: "west-st-louis-county-mo",
      name: "West St. Louis County",
      state: "Missouri",
      stateCode: "MO",
      teaser: "West County guides for suburban cities tied to the St. Louis County court system.",
      urgentDeadline: {
        headline: "West County DWI timing is local on the front end but county-wide in the court system.",
        body: "Drivers often start with a city or precinct-level police question and then shift quickly into the larger St. Louis County court and license process.",
      },
      regionHighlights: [
        {
          title: "Manchester Road and I-64 shape the region",
          body: "Ballwin, Ellisville, Manchester, Chesterfield, and Wildwood share major commuter corridors, which means enforcement often follows the same traffic spine even when city boundaries change quickly.",
        },
        {
          title: "County court, suburban records",
          body: "This cluster is a good example of why a region page matters: local police contacts vary by suburb, but the court path still pulls readers back toward Clayton and the county system.",
        },
        {
          title: "Wildwood has a different policing setup",
          body: "Wildwood relies on St. Louis County Police rather than a standalone municipal department, which makes the regional explanation more important than a city-only template would suggest.",
        },
        {
          title: "License logistics stay practical",
          body: "The West County license office is often a more useful next step for drivers than the courthouse itself when the immediate question is about reinstatement or documents.",
        },
      ],
      processNotes: [
        {
          label: "Suburban overlap",
          title: "City boundaries change fast in West County",
          body: "Readers can move from one municipality to another in minutes, so it helps to confirm which department handled the stop or crash before requesting records.",
        },
        {
          label: "County pull",
          title: "The case path usually gets bigger than the city",
          body: "Even when a Ballwin or Chesterfield officer starts the case, the next steps often require county-court navigation and county-level timing awareness.",
        },
        {
          label: "Wildwood exception",
          title: "Some cities in this cluster do not fit the same policing model",
          body: "Wildwood readers, in particular, benefit from the region page because local enforcement runs through St. Louis County Police rather than a city force.",
        },
      ],
      court: {
        name: "St. Louis County Circuit Court",
        address: "105 S. Central Avenue, Clayton, MO 63105",
        phone: "(314) 615-8029",
        hours: "Monday-Friday, 8:00 am-5:00 pm",
        courtSystem: "21st Judicial Circuit",
        href: "https://stlcountycourts.com/",
      },
      licenseOffice: {
        name: "West County License Office",
        type: "Missouri License Office",
        address: "15533 Manchester Road, Ballwin, MO 63011",
        phone: "(636) 230-5041",
        hours: "Confirm current hours with the Missouri Department of Revenue office locator.",
        href: "https://dor.mo.gov/license-office-locator/",
        note: "Missouri DOR license office serving many West County driver-license and motor-vehicle transactions.",
      },
      cities: [
        {
          slug: "ballwin-mo",
          name: "Ballwin",
          agency: "Ballwin Police Department",
          police: {
            name: "Ballwin Police Department",
            type: "Municipal Police",
            address: "302 Kehrs Mill Road, Ballwin, MO 63011",
            phone: "(636) 227-9000",
            href: "https://ballwin.mo.us/Contact-Us/",
            note: "For Ballwin police reports, crash records, and municipal enforcement questions.",
          },
        },
        {
          slug: "chesterfield-mo",
          name: "Chesterfield",
          agency: "Chesterfield Police Department",
          police: {
            name: "Chesterfield Police Department",
            type: "Municipal Police",
            address: "690 Chesterfield Parkway W., Chesterfield, MO 63017",
            phone: "(636) 537-3000",
            href: "https://www.chesterfield.mo.us/police-department.html",
            note: "For Chesterfield police reports, crash records, and local enforcement questions.",
          },
        },
        {
          slug: "ellisville-mo",
          name: "Ellisville",
          agency: "Ellisville Police Department",
          police: {
            name: "Ellisville Police Department",
            type: "Municipal Police",
            address: "1 Weis Avenue, Ellisville, MO 63011",
            phone: "(636) 227-7777",
            href: "https://www.ellisville.mo.us/Directory.aspx?did=9",
            note: "For Ellisville police reports, crash records, and local enforcement questions.",
          },
        },
        {
          slug: "manchester-mo",
          name: "Manchester",
          agency: "Manchester Police Department",
          police: {
            name: "Manchester Police Department",
            type: "Municipal Police",
            address: "200 Highlands Boulevard Drive, Manchester, MO 63011",
            phone: "(636) 227-1410",
            href: "https://www.manchestermo.gov/160/Police",
            note: "For Manchester police records, local crash reports, and city enforcement questions.",
          },
        },
        {
          slug: "wildwood-mo",
          name: "Wildwood",
          agency: "St. Louis County Police Department",
          police: {
            name: "St. Louis County Police Department - West County Precinct",
            type: "County Police",
            address: "232 Vance Road Suite 101, Valley Park, MO 63088",
            phone: "(314) 615-0700",
            href: "https://www.stlouiscountypolice.com/precincts/west-county/",
            note: "Wildwood does not operate a separate municipal police department; St. Louis County Police provide local coverage.",
          },
        },
      ],
    },
    {
      slug: "charlotte-south-nc",
      name: "Charlotte South",
      state: "North Carolina",
      stateCode: "NC",
      teaser: "South Charlotte community guides covering a compact, fast-moving legal market.",
      urgentDeadline: {
        headline: "North Carolina DWI consequences can start immediately after the stop.",
        body: "In the Charlotte South cluster, the early pressure point is often sorting out which county court and DMV path apply before deadlines or revocation issues start stacking up.",
      },
      regionHighlights: [
        {
          title: "Two counties inside one sponsorable market",
          body: "This cluster mixes Mecklenburg-based communities with Indian Trail in Union County, which creates a stronger business package but also means court and sheriff paths are not identical.",
        },
        {
          title: "Charlotte traffic corridors shape local demand",
          body: "I-485, South Boulevard, Providence Road, and Monroe-area commuter routes create a dense pattern of stops, crashes, and records questions across a relatively compact geography.",
        },
        {
          title: "CMPD and county coverage both matter",
          body: "Ballantyne depends on Charlotte-Mecklenburg Police, while Indian Trail uses the Union County Sheriff's Office, so readers need region context before a city page alone makes full sense.",
        },
        {
          title: "Court location depends on the side of the market",
          body: "Matthews, Pineville, and Ballantyne readers typically orient around Mecklenburg County, while Indian Trail points readers toward Union County in Monroe.",
        },
      ],
      processNotes: [
        {
          label: "County split",
          title: "Start by confirming whether Mecklenburg or Union County controls the case",
          body: "That one distinction changes the courthouse, the clerk path, and often the fastest way to verify court information.",
        },
        {
          label: "Regional commuting",
          title: "This market acts more like one traffic zone than four isolated towns",
          body: "People drive these communities interchangeably, so a regional overview helps users and potential sponsors understand why one package covers all four cities.",
        },
        {
          label: "DMV and court timing",
          title: "DMV questions can become urgent before the court process feels clear",
          body: "That is especially true in North Carolina, where readers often want the right DMV office and the right courthouse in the same first conversation.",
        },
      ],
      licenseOffice: {
        name: "NCDMV Driver License Office - Charlotte South",
        type: "NCDMV Driver License Office",
        address: "201-H W. Arrowood Road, Charlotte, NC 28217",
        phone: "(704) 527-2562",
        hours: "Confirm current hours with the NCDMV office locator.",
        href: "https://www.ncdot.gov/dmv/offices-services/locate-dmv-office/Pages/dmv-offices.aspx",
        note: "Use the NCDMV locator to verify wait times, hours, and whether an appointment is required.",
      },
      cities: [
        {
          slug: "ballantyne-nc",
          name: "Ballantyne",
          agency: "Charlotte-Mecklenburg Police Department",
          police: {
            name: "Charlotte-Mecklenburg Police Department - South Division",
            type: "Municipal Police",
            address: "8050 Corporate Center Drive, Charlotte, NC 28226",
            phone: "(704) 336-3000",
            href: "https://www.charlottenc.gov/cmpd/Organization/Patrol-Divisions/South-Division",
            note: "Ballantyne is within Charlotte-Mecklenburg Police Department service territory; confirm the responding division for a specific incident.",
          },
          courtOverride: {
            name: "Mecklenburg County Courthouse",
            address: "832 E. Fourth Street, Charlotte, NC 28202",
            phone: "(704) 686-0400",
            hours: "Monday-Friday, 9:00 am-5:00 pm",
            courtSystem: "North Carolina Judicial Branch",
            href: "https://www.nccourts.gov/locations/mecklenburg-county/mecklenburg-county-courthouse",
          },
        },
        {
          slug: "indian-trail-nc",
          name: "Indian Trail",
          agency: "Union County Sheriff's Office",
          police: {
            name: "Union County Sheriff's Office",
            type: "County Sheriff",
            address: "3344 Presson Road, Monroe, NC 28112",
            phone: "(704) 283-3789",
            href: "https://www.unioncountysheriffsoffice.com/",
            note: "Indian Trail contracts with the Union County Sheriff's Office for local law-enforcement services.",
          },
          courtOverride: {
            name: "Union County Judicial Center",
            address: "400 N. Main Street, Monroe, NC 28112",
            phone: "(704) 698-3100",
            hours: "Monday-Friday, 8:30 am-5:00 pm",
            courtSystem: "North Carolina Judicial Branch",
            href: "https://www.nccourts.gov/locations/union-county/union-county-judicial-center",
          },
          licenseOfficeOverride: {
            name: "NCDMV Driver License Office - Monroe",
            type: "NCDMV Driver License Office",
            address: "3122 W. Highway 74, Monroe, NC 28110",
            phone: "(704) 283-4264",
            hours: "Confirm current hours with the NCDMV office locator.",
            href: "https://www.ncdot.gov/dmv/offices-services/locate-dmv-office/Pages/dmv-offices.aspx",
            note: "Use the NCDMV locator to verify services, appointments, and current hours before visiting.",
          },
        },
        {
          slug: "matthews-nc",
          name: "Matthews",
          agency: "Matthews Police Department",
          police: {
            name: "Matthews Police Department",
            type: "Municipal Police",
            address: "1201 Crews Road, Matthews, NC 28105",
            phone: "(704) 847-5555",
            href: "https://www.matthewsnc.gov/pview.aspx?id=20710",
            note: "For Matthews police records, crash reports, and local law-enforcement questions.",
          },
          courtOverride: {
            name: "Mecklenburg County Courthouse",
            address: "832 E. Fourth Street, Charlotte, NC 28202",
            phone: "(704) 686-0400",
            hours: "Monday-Friday, 9:00 am-5:00 pm",
            courtSystem: "North Carolina Judicial Branch",
            href: "https://www.nccourts.gov/locations/mecklenburg-county/mecklenburg-county-courthouse",
          },
        },
        {
          slug: "pineville-nc",
          name: "Pineville",
          agency: "Pineville Police Department",
          police: {
            name: "Pineville Police Department",
            type: "Municipal Police",
            address: "427 Main Street, Pineville, NC 28134",
            phone: "(704) 889-2231",
            href: "https://www.pinevillenc.gov/government/departments/police/",
            note: "For Pineville police records, crash reports, and city enforcement questions.",
          },
          courtOverride: {
            name: "Mecklenburg County Courthouse",
            address: "832 E. Fourth Street, Charlotte, NC 28202",
            phone: "(704) 686-0400",
            hours: "Monday-Friday, 9:00 am-5:00 pm",
            courtSystem: "North Carolina Judicial Branch",
            href: "https://www.nccourts.gov/locations/mecklenburg-county/mecklenburg-county-courthouse",
          },
        },
      ],
    },
    {
      slug: "raleigh-north-nc",
      name: "Raleigh North",
      state: "North Carolina",
      stateCode: "NC",
      teaser: "North Raleigh suburbs with separate district and DMV touchpoints.",
      urgentDeadline: {
        headline: "Wake County DWI paperwork can feel centralized even when the stop happened in the suburbs.",
        body: "North Raleigh, Wake Forest, Rolesville, and Knightdale readers still need a fast read on the Wake County court path and DMV consequences.",
      },
      regionHighlights: [
        {
          title: "One county, different suburban entry points",
          body: "Knightdale, Rolesville, Wake Forest, and North Raleigh all feed into Wake County systems, but they sit on different commuter and enforcement corridors including I-540, Capital Boulevard, and US-1.",
        },
        {
          title: "Wake County centralization matters",
          body: "Many criminal-case questions point back to the Wake County Justice Center, while civil matters may point to the Wake County Courthouse, which is why the region page works as a bridge between suburb-level searches and county-level procedure.",
        },
        {
          title: "DMV and court are not in the same place",
          body: "The county court anchor and the driver-license office are different trips with different workflows, so the regional page helps readers keep those systems separate.",
        },
        {
          title: "Fast-growth suburbs change local search intent",
          body: "People often search by town first, but the real next steps can be county-based, especially for DWI court dates, records, and license questions.",
        },
      ],
      processNotes: [
        {
          label: "Wake County hub",
          title: "Use the Justice Center as the county-wide court reference",
          body: "Even when the police contact happened in Rolesville or Wake Forest, the regional page helps explain the shared county court path.",
        },
        {
          label: "Corridor differences",
          title: "Major roads can change the first agency involved",
          body: "Stops near major commuter corridors can involve different local departments, so the city page still matters after the regional orientation step.",
        },
        {
          label: "Separate trips",
          title: "Court and DMV tasks usually require different planning",
          body: "The region page keeps that practical distinction visible instead of letting readers assume every next step happens in one building.",
        },
      ],
      court: {
        name: "Wake County Justice Center",
        address: "300 S. Salisbury Street, Raleigh, NC 27601",
        phone: "(919) 792-4000",
        hours: "Monday-Friday, 8:30 am-5:00 pm",
        courtSystem: "North Carolina Judicial Branch",
        href: "https://www.nccourts.gov/locations/wake-county/wake-county-justice-center",
      },
      personalInjuryCourt: {
        name: "Wake County Courthouse",
        address: "316 Fayetteville Street Mall, Raleigh, NC 27601",
        phone: "(919) 792-4000",
        hours: "Monday-Friday, 8:30 am-5:00 pm",
        courtSystem: "North Carolina Judicial Branch",
        href: "https://www.nccourts.gov/locations/wake-county/wake-county-courthouse",
      },
      licenseOffice: {
        name: "NCDMV Driver License Office - Raleigh",
        type: "NCDMV Driver License Office",
        address: "2431 Spring Forest Road, Raleigh, NC 27615",
        phone: "(919) 855-6877",
        hours: "Confirm current hours with the NCDMV office locator.",
        href: "https://www.ncdot.gov/dmv/offices-services/locate-dmv-office/Pages/dmv-offices.aspx",
        note: "Use the NCDMV locator to verify services, appointments, and current hours before visiting.",
      },
      cities: [
        {
          slug: "knightdale-nc",
          name: "Knightdale",
          agency: "Knightdale Police Department",
          police: {
            name: "Knightdale Police Department",
            type: "Municipal Police",
            address: "979 Steeple Square Court, Knightdale, NC 27545",
            phone: "(919) 217-2261",
            href: "https://www.knightdalenc.gov/departments/police",
            note: "For Knightdale police reports, crash records, and local enforcement questions.",
          },
        },
        {
          slug: "north-raleigh-nc",
          name: "North Raleigh",
          agency: "Raleigh Police Department",
          police: {
            name: "Raleigh Police Department",
            type: "Municipal Police",
            address: "6716 Six Forks Road, Raleigh, NC 27615",
            phone: "(919) 996-3335",
            href: "https://raleighnc.gov/police",
            note: "For Raleigh police reports, crash records, and city enforcement questions in North Raleigh.",
          },
        },
        {
          slug: "rolesville-nc",
          name: "Rolesville",
          agency: "Rolesville Police Department",
          police: {
            name: "Rolesville Police Department",
            type: "Municipal Police",
            address: "502 Southtown Circle, Rolesville, NC 27571",
            phone: "(919) 554-7222",
            href: "https://www.rolesvillenc.gov/police",
            note: "For Rolesville police records, crash reports, and local enforcement questions.",
          },
        },
        {
          slug: "wake-forest-nc",
          name: "Wake Forest",
          agency: "Wake Forest Police Department",
          police: {
            name: "Wake Forest Police Department",
            type: "Municipal Police",
            address: "225 S. Taylor Street, Wake Forest, NC 27587",
            phone: "(919) 554-6150",
            href: "https://www.wakeforestnc.gov/police",
            note: "For Wake Forest police reports, crash records, and local enforcement questions.",
          },
        },
      ],
    },
    {
      slug: "wake-southwest-nc",
      name: "Wake Southwest",
      state: "North Carolina",
      stateCode: "NC",
      teaser: "Wake County south and southwest city guides tied to the county court and state agency systems.",
      urgentDeadline: {
        headline: "Wake Southwest DWI cases can feel local at the stop and county-wide by the next morning.",
        body: "Apex, Cary, Holly Springs, and Fuquay-Varina readers often need both the Wake County court path and the right DMV office immediately.",
      },
      regionHighlights: [
        {
          title: "Rapid-growth triangle suburbs",
          body: "Apex, Cary, Holly Springs, and Fuquay-Varina sit along fast-moving Triangle commuter corridors where population growth, heavy driving, and overlapping travel patterns create steady local search demand.",
        },
        {
          title: "Wake County court system is the common thread",
          body: "Although each town has its own police department, the court path still points back to Wake County court offices in Raleigh, giving the cluster real shared logic beyond pure geography.",
        },
        {
          title: "DMV convenience changes by city",
          body: "Cary and Fuquay-Varina have different practical DMV touchpoints, so city pages matter, but the region page still helps readers understand the larger county process first.",
        },
        {
          title: "Town identity stays strong",
          body: "These towns are close together but not interchangeable, which is why a strong sponsor package benefits from both a county-level page and city-level guides.",
        },
      ],
      processNotes: [
        {
          label: "Shared county court",
          title: "Wake County is the unifying process layer",
          body: "This cluster works well because local police vary by town while court scheduling and broader case structure still run through the same county system.",
        },
        {
          label: "Southwest DMV choices",
          title: "Drivers often care about the nearest workable DMV office, not just the county seat",
          body: "That is why the city pages keep their own office references even while the regional page explains the shared legal path.",
        },
        {
          label: "Commuter market",
          title: "The region reflects how people actually move through southwest Wake",
          body: "Residents commute between these towns constantly, so one sponsor package across all four cities feels intuitive instead of forced.",
        },
      ],
      court: {
        name: "Wake County Justice Center",
        address: "300 S. Salisbury Street, Raleigh, NC 27601",
        phone: "(919) 792-4000",
        hours: "Monday-Friday, 8:30 am-5:00 pm",
        courtSystem: "North Carolina Judicial Branch",
        href: "https://www.nccourts.gov/locations/wake-county/wake-county-justice-center",
      },
      personalInjuryCourt: {
        name: "Wake County Courthouse",
        address: "316 Fayetteville Street Mall, Raleigh, NC 27601",
        phone: "(919) 792-4000",
        hours: "Monday-Friday, 8:30 am-5:00 pm",
        courtSystem: "North Carolina Judicial Branch",
        href: "https://www.nccourts.gov/locations/wake-county/wake-county-courthouse",
      },
      licenseOffice: {
        name: "NCDMV Driver License Office - Raleigh",
        type: "NCDMV Driver License Office",
        address: "3231 Avent Ferry Road, Raleigh, NC 27606",
        phone: "(919) 816-9128",
        hours: "Confirm current hours with the NCDMV office locator.",
        href: "https://www.ncdot.gov/dmv/offices-services/locate-dmv-office/Pages/dmv-offices.aspx",
        note: "Use the NCDMV locator to verify services, appointments, and current hours before visiting.",
      },
      cities: [
        {
          slug: "apex-nc",
          name: "Apex",
          agency: "Apex Police Department",
          police: {
            name: "Apex Police Department",
            type: "Municipal Police",
            address: "205 Saunders Street, Apex, NC 27502",
            phone: "(919) 362-8661",
            href: "https://www.apexnc.org/261/Police-Department",
            note: "For Apex police reports, crash records, and local enforcement questions.",
          },
          licenseOfficeOverride: {
            name: "NCDMV Driver License Office - Cary",
            type: "NCDMV Driver License Office",
            address: "1387 SE Maynard Road, Cary, NC 27511",
            phone: "(919) 468-0319",
            hours: "Confirm current hours with the NCDMV office locator.",
            href: "https://www.ncdot.gov/dmv/offices-services/locate-dmv-office/Pages/dmv-offices.aspx",
            note: "Use the NCDMV locator to verify services, appointments, and current hours before visiting.",
          },
        },
        {
          slug: "cary-nc",
          name: "Cary",
          agency: "Cary Police Department",
          police: {
            name: "Cary Police Department",
            type: "Municipal Police",
            address: "120 Wilkinson Avenue, Cary, NC 27513",
            phone: "(919) 469-4012",
            href: "https://www.carync.gov/services-publications/police",
            note: "For Cary police reports, crash records, and local enforcement questions.",
          },
          licenseOfficeOverride: {
            name: "NCDMV Driver License Office - Cary",
            type: "NCDMV Driver License Office",
            address: "1387 SE Maynard Road, Cary, NC 27511",
            phone: "(919) 468-0319",
            hours: "Confirm current hours with the NCDMV office locator.",
            href: "https://www.ncdot.gov/dmv/offices-services/locate-dmv-office/Pages/dmv-offices.aspx",
            note: "Use the NCDMV locator to verify services, appointments, and current hours before visiting.",
          },
        },
        {
          slug: "fuquay-varina-nc",
          name: "Fuquay-Varina",
          agency: "Fuquay-Varina Police Department",
          police: {
            name: "Fuquay-Varina Police Department",
            type: "Municipal Police",
            address: "401 Old Honeycutt Road, Fuquay-Varina, NC 27526",
            phone: "(919) 552-3191",
            href: "https://www.fuquay-varina.org/223/Police",
            note: "For Fuquay-Varina police reports, crash records, and local enforcement questions.",
          },
          licenseOfficeOverride: {
            name: "NCDMV Driver License Office - Fuquay-Varina",
            type: "NCDMV Driver License Office",
            address: "131 S. Fuquay Avenue, Fuquay-Varina, NC 27526",
            phone: "(919) 552-1895",
            hours: "Confirm current hours with the NCDMV office locator.",
            href: "https://www.ncdot.gov/dmv/offices-services/locate-dmv-office/Pages/dmv-offices.aspx",
            note: "Use the NCDMV locator to verify services, appointments, and current hours before visiting.",
          },
        },
        {
          slug: "holly-springs-nc",
          name: "Holly Springs",
          agency: "Holly Springs Police Department",
          police: {
            name: "Holly Springs Police Department",
            type: "Municipal Police",
            address: "750 Holly Springs Road, Holly Springs, NC 27540",
            phone: "(919) 557-9111",
            href: "https://www.hollyspringsnc.gov/318/Police",
            note: "For Holly Springs police reports, crash records, and local enforcement questions.",
          },
          licenseOfficeOverride: {
            name: "NCDMV Driver License Office - Fuquay-Varina",
            type: "NCDMV Driver License Office",
            address: "131 S. Fuquay Avenue, Fuquay-Varina, NC 27526",
            phone: "(919) 552-1895",
            hours: "Confirm current hours with the NCDMV office locator.",
            href: "https://www.ncdot.gov/dmv/offices-services/locate-dmv-office/Pages/dmv-offices.aspx",
            note: "Use the NCDMV locator to verify services, appointments, and current hours before visiting.",
          },
        },
      ],
    },
  ],
};
